name: Deploy to Azure App Service (pmmic)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Si prefieres que Azure construya con Oryx, puedes omitir estos dos pasos de Node.
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: pmmic
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}
          package: .
           clean: true